server:
  port: 9000
  http:
    protocal: http://
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix:
    suffix: .html
    cache: false

  host:
    server: ${server.http.protocal}localhost:9000
    static: ${server.http.protocal}localhost:9000
    auth: ${server.http.protocal}localhost:9000
    console: ${server.http.protocal}localhost:9000
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.90:27017/hookah
  mvc:
      static-path-pattern: /static/**
