server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: galaxybigdata.com
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false

  host:
    domain: galaxybigdata.com
    website: ${server.http.protocal}www.galaxybigdata.com
    static: ${server.http.protocal}static.galaxybigdata.com
    auth: ${server.http.protocal}auth.galaxybigdata.com
    console: ${server.http.protocal}console.galaxybigdata.com
    admin: ${server.http.protocal}admin.galaxybigdata.com
    crowd: ${server.http.protocal}crowd.galaxybigdata.com
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.galaxybigdata.com/reg
    loginUrl: http://auth.galaxybigdata.com/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.galaxybigdata.com/logout?redirect_uri=http://www.galaxybigdata.com/login
    accessTokenUrl: http://auth.galaxybigdata.com/oauth/accessToken
    userInfoUrl: http://auth.galaxybigdata.com/userInfo
    redirectUrl: http://auth.galaxybigdata.com/login
  redis:
    ipPort: 192.168.15.174:7000,192.168.15.174:7001,192.168.15.174:7002
  consul:
    ipPort: 127.0.0.1:8500
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.175:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 192.168.15.174:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /
      listener:
        retry:
        enabled: true
        max-attempts: 2