server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: hookah.app
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false

  host:
    domain: hookah.app
    website: ${server.http.protocal}www.hookah.app
    static: ${server.http.protocal}static.hookah.app
    auth: ${server.http.protocal}auth.hookah.app
    console: ${server.http.protocal}console.hookah.app
    admin: ${server.http.protocal}admin.hookah.app
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.hookah.app/reg
    loginUrl: http://auth.hookah.app/oauth/authorize?client_id=website&response_type=code&redirect_uri=http://www.hookah.app/login
    logoutUrl: http://auth.hookah.app/logout?redirect_uri=http://www.hookah.app/login
    accessTokenUrl: http://auth.hookah.app/oauth/accessToken
    userInfoUrl: http://auth.hookah.app/userInfo
    redirectUrl: http://auth.hookah.app/login
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.90:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 192.168.200.116:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /
redis:
  ip: 192.168.15.90
  port: 6379
  password: Yqn2ht4DYkMHlDvTY7CV
  pool:
    #最大分配的对象数
    maxTotal: 1024
    #最大能够保持idel状态的对象数
    maxIdle: 200
    #当调用borrow Object方法时，是否进行有效性检查
    testOnBorrow: false


