server:
  port: 9000
  http:
    protocal: http://
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix:
    suffix: .html
    cache: false

  host:
    website: ${server.http.protocal}www.hookah.test
    static: ${server.http.protocal}static.hookah.test
    auth: ${server.http.protocal}auth.hookah.test
    console: ${server.http.protocal}console.hookah.test
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.hookah.test/reg
    loginUrl: http://auth.hookah.test/oauth/authorize?client_id=website&response_type=code&redirect_uri=http://localhost:9000/login
    logoutUrl: http://auth.hookah.test/logout?redirect_uri=http://localhost:9000/login
    accessTokenUrl: http://auth.hookah.test/oauth/accessToken
    userInfoUrl: http://auth.hookah.test/userInfo
    redirectUrl: http://auth.hookah.test/login
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.90:27017/hookah
  mvc:
      static-path-pattern: /static/**
