server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: lsdashuju.net
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false

  host:
    domain: lsdashuju.net
    website: ${server.http.protocal}www.lsdashuju.net
    static: ${server.http.protocal}static.lsdashuju.net
    auth: ${server.http.protocal}auth.lsdashuju.net
    console: ${server.http.protocal}console.lsdashuju.net
    admin: ${server.http.protocal}admin.lsdashuju.net
    crowd: ${server.http.protocal}crowd.lsdashuju.net
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.lsdashuju.net/reg
    loginUrl: http://auth.lsdashuju.net/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.lsdashuju.net/logout?redirect_uri=http://www.lsdashuju.net/login
    accessTokenUrl: http://auth.lsdashuju.net/oauth/accessToken
    userInfoUrl: http://auth.lsdashuju.net/userInfo
    redirectUrl: http://auth.lsdashuju.net/login
  redis:
    ipPort: 192.168.1.201:7000,192.168.1.201:7001,192.168.1.201:7002
    password: bdgstore
  consul:
    ipPort: localhost:8500
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.1.201:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 192.168.1.201:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /
      listener:
        retry:
        enabled: true
        max-attempts: 2