server:
  port: 9000
  http:
    protocal: http://
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix:
    suffix: .html
    cache: false

  host:
    website: ${server.http.protocal}www.hookah.test
    static: ${server.http.protocal}static.hookah.test
    auth: ${server.http.protocal}auth.hookah.test
    console: ${server.http.protocal}console.hookah.test
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.hookah.test/reg
    loginUrl: http://auth.hookah.test/oauth/authorize?client_id=website&response_type=code&redirect_uri=http://www.hookah.test/login
    logoutUrl: http://auth.hookah.test/logout?redirect_uri=http://www.hookah.test/login
    accessTokenUrl: http://auth.hookah.test/oauth/accessToken
    userInfoUrl: http://auth.hookah.test/userInfo
    redirectUrl: http://auth.hookah.test/login
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.90:27017/hookah
  mvc:
      static-path-pattern: /static/**
redis:
  ip: 192.168.15.90
  port: 6379
  password: Yqn2ht4DYkMHlDvTY7CV
  pool:
    #最大分配的对象数
    maxTotal: 1024
    #最大能够保持idel状态的对象数
    maxIdle: 200
    #当调用borrow Object方法时，是否进行有效性检查
    testOnBorrow: false
