package com.jusfoun.hookah.core.dao.jf;

import com.jusfoun.hookah.core.domain.jf.JfSource;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface JfSourceMapper extends GenericDao<ZbRefundRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_source
     *
     * @mbggenerated
     */
    int insert(JfSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_source
     *
     * @mbggenerated
     */
    int insertSelective(JfSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_source
     *
     * @mbggenerated
     */
    JfSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JfSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JfSource record);
}