package com.jusfoun.hookah.core.domain.zb;

import com.jusfoun.hookah.core.generic.GenericModel;
import java.util.Date;

public class zbRecommend extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.requirement_id
     *
     * @mbggenerated
     */
    private Integer requirementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_recommend.recommend_length
     *
     * @mbggenerated
     */
    private Integer recommendLength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.id
     *
     * @return the value of zb_recommend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.id
     *
     * @param id the value for zb_recommend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.requirement_id
     *
     * @return the value of zb_recommend.requirement_id
     *
     * @mbggenerated
     */
    public Integer getRequirementId() {
        return requirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.requirement_id
     *
     * @param requirementId the value for zb_recommend.requirement_id
     *
     * @mbggenerated
     */
    public void setRequirementId(Integer requirementId) {
        this.requirementId = requirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.order_num
     *
     * @return the value of zb_recommend.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.order_num
     *
     * @param orderNum the value for zb_recommend.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.add_time
     *
     * @return the value of zb_recommend.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.add_time
     *
     * @param addTime the value for zb_recommend.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.update_time
     *
     * @return the value of zb_recommend.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.update_time
     *
     * @param updateTime the value for zb_recommend.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.user_id
     *
     * @return the value of zb_recommend.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.user_id
     *
     * @param userId the value for zb_recommend.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.status
     *
     * @return the value of zb_recommend.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.status
     *
     * @param status the value for zb_recommend.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_recommend.recommend_length
     *
     * @return the value of zb_recommend.recommend_length
     *
     * @mbggenerated
     */
    public Integer getRecommendLength() {
        return recommendLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_recommend.recommend_length
     *
     * @param recommendLength the value for zb_recommend.recommend_length
     *
     * @mbggenerated
     */
    public void setRecommendLength(Integer recommendLength) {
        this.recommendLength = recommendLength;
    }
}