server:
  port: 9600
  http:
    protocal: http://
myconf:
  host:
    domain: weifangdata.com
    website: ${server.http.protocal}www.weifangdata.com
    static: ${server.http.protocal}static.weifangdata.com
    auth: ${server.http.protocal}auth.weifangdata.com
    console: ${server.http.protocal}console.weifangdata.com
debug: true
spring:
  data:
    mongodb:
      uri: mongodb://172.16.201.42:27017/hookah
  mvc:
      static-path-pattern: /static/**
  http:
        multipart:
            maxFileSize: 20Mb
            maxRequestSize: 20Mb
upload:
  file-path: /webapp/static/
  replace-path: /target
  url: http://localhost:9600/