server:
  port: 9600
  http:
    protocal: http://
myconf:
  host:
    domain: galaxybigdata.com
    website: ${server.http.protocal}www.galaxybigdata.com
    static: ${server.http.protocal}static.galaxybigdata.com
    auth: ${server.http.protocal}auth.galaxybigdata.com
    console: ${server.http.protocal}console.galaxybigdata.com
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.90:27017/bdgStore
  mvc:
      static-path-pattern: /static/**
  http:
        multipart:
            maxFileSize: 20Mb
            maxRequestSize: 20Mb
upload:
  file-path: /webapp/static/
  replace-path: /target
  url: http://localhost:9600/