server:
  port: 9600
  http:
    protocal: http://
myconf:
  host:
    domain: qddata.com.cn
    website: ${server.http.protocal}trade.qddata.com.cn
    static: ${server.http.protocal}static.qddata.com.cn
    auth: ${server.http.protocal}auth.qddata.com.cn
    console: ${server.http.protocal}console.qddata.com.cn
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.90:27017/hookah
  mvc:
      static-path-pattern: /static/**
  http:
        multipart:
            maxFileSize: 20Mb
            maxRequestSize: 20Mb
upload:
  file-path: /webapp/static/
  replace-path: /target
  url: http://localhost:9600/