server:
  port: 9600
  http:
    protocal: http://
myconf:
  host:
    domain: bdgstore.cn
    website: ${server.http.protocal}www.bdgstore.cn
    static: ${server.http.protocal}static.bdgstore.cn
    auth: ${server.http.protocal}auth.bdgstore.cn
    console: ${server.http.protocal}console.bdgstore.cn
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.15.203:27017/bdgStore
  mvc:
      static-path-pattern: /static/**
  http:
        multipart:
            maxFileSize: 20Mb
            maxRequestSize: 20Mb
upload:
  file-path: /webapp/static/
  replace-path: /target
  url: http://localhost:9600/