package com.jusfoun.hookah.core.dao;

import com.jusfoun.hookah.core.domain.ExpressInfo;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface ExpressInfoMapper extends GenericDao<ExpressInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String expressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_info
     *
     * @mbggenerated
     */
    int insert(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_info
     *
     * @mbggenerated
     */
    int insertSelective(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_info
     *
     * @mbggenerated
     */
    ExpressInfo selectByPrimaryKey(String expressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExpressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExpressInfo record);
}