package com.jusfoun.hookah.core.dao;

import com.jusfoun.hookah.core.domain.GoodsAttrType;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface GoodsAttrTypeMapper extends GenericDao<GoodsAttrType> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_attr_type
     *
     * @mbggenerated
     */
    int insert(GoodsAttrType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_attr_type
     *
     * @mbggenerated
     */
    int insertSelective(GoodsAttrType record);
}