package com.jusfoun.hookah.core.dao;

import com.jusfoun.hookah.core.domain.PayAccountRecord;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface PayAccountRecordMapper extends GenericDao<PayAccountRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account_record
     *
     * @mbggenerated
     */
    int insert(PayAccountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account_record
     *
     * @mbggenerated
     */
    int insertSelective(PayAccountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account_record
     *
     * @mbggenerated
     */
    PayAccountRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayAccountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayAccountRecord record);
}