package com.jusfoun.hookah.core.dao;

import com.jusfoun.hookah.core.domain.SysRoleGroup;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface SysRoleGroupMapper extends GenericDao<SysRoleGroup> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_group
     *
     * @mbggenerated
     */
    int insert(SysRoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_group
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_group
     *
     * @mbggenerated
     */
    SysRoleGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoleGroup record);
}