package com.jusfoun.hookah.core.dao;

import com.jusfoun.hookah.core.domain.UserRole;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface UserRoleMapper extends GenericDao<UserRole> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated
     */
    int insertSelective(UserRole record);
}