package com.jusfoun.hookah.oauth2server.dao;

import com.jusfoun.hookah.core.domain.OauthClient;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface OauthClientMapper extends GenericDao<OauthClient> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int insert(OauthClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int insertSelective(OauthClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    OauthClient selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OauthClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OauthClient record);

    OauthClient selectByClientId(String clientId);
}