package com.jusfoun.hookah.core.dao.zb;

import com.jusfoun.hookah.core.domain.zb.ZbProgramiFles;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface ZbProgramiFlesMapper extends GenericDao<ZbProgramiFles> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_program_files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_program_files
     *
     * @mbggenerated
     */
    int insert(ZbProgramiFles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_program_files
     *
     * @mbggenerated
     */
    int insertSelective(ZbProgramiFles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_program_files
     *
     * @mbggenerated
     */
    ZbProgramiFles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_program_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZbProgramiFles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_program_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZbProgramiFles record);
}