package com.jusfoun.hookah.core.dao.zb;

import com.jusfoun.hookah.core.dao.GenericDao;
import com.jusfoun.hookah.core.domain.zb.ZbRequirementTag;

public interface ZbRequirementTagMapper extends GenericDao<ZbRequirementTag> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_requirement_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_requirement_tag
     *
     * @mbggenerated
     */
    int insert(ZbRequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_requirement_tag
     *
     * @mbggenerated
     */
    int insertSelective(ZbRequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_requirement_tag
     *
     * @mbggenerated
     */
    ZbRequirementTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_requirement_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZbRequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_requirement_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZbRequirementTag record);
}