package com.jusfoun.hookah.core.dao.zb;

import com.jusfoun.hookah.core.domain.zb.ZbTrusteeRecord;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface ZbTrusteeRecordMapper extends GenericDao<ZbTrusteeRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_trustee_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_trustee_record
     *
     * @mbggenerated
     */
    int insert(ZbTrusteeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_trustee_record
     *
     * @mbggenerated
     */
    int insertSelective(ZbTrusteeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_trustee_record
     *
     * @mbggenerated
     */
    ZbTrusteeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_trustee_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZbTrusteeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_trustee_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZbTrusteeRecord record);
}