package com.jusfoun.hookah.core.dao.zb;

import com.jusfoun.hookah.core.domain.zb.ZbUser;
import com.jusfoun.hookah.core.generic.GenericDao;

public interface ZbUserMapper extends GenericDao<ZbUser> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    int insert(ZbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    int insertSelective(ZbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    ZbUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ZbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZbUser record);
}