package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.data.annotation.Id;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import java.util.Date;

public class Cart extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.rec_id
     *
     * @mbggenerated
     */
    @Id
    @javax.persistence.Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_sn
     *
     * @mbggenerated
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.market_price
     *
     * @mbggenerated
     */
    @Digits(integer=10,fraction = 2)
    private Float marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_price
     *
     * @mbggenerated
     */
    @Digits(integer=10,fraction = 2)
    private Float goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_format
     *
     * @mbggenerated
     */
    private String goodsFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_number
     *
     * @mbggenerated
     */
    @Min(1)
    private Short goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.rec_type
     *
     * @mbggenerated
     */
    private Byte recType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.is_gift
     *
     * @mbggenerated
     */
    private Short isGift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.add_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.rec_id
     *
     * @return the value of cart.rec_id
     *
     * @mbggenerated
     */
    public String getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.rec_id
     *
     * @param recId the value for cart.rec_id
     *
     * @mbggenerated
     */
    public void setRecId(String recId) {
        this.recId = recId == null ? null : recId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goods_id
     *
     * @return the value of cart.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goods_id
     *
     * @param goodsId the value for cart.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goods_sn
     *
     * @return the value of cart.goods_sn
     *
     * @mbggenerated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goods_sn
     *
     * @param goodsSn the value for cart.goods_sn
     *
     * @mbggenerated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goods_name
     *
     * @return the value of cart.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goods_name
     *
     * @param goodsName the value for cart.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.market_price
     *
     * @return the value of cart.market_price
     *
     * @mbggenerated
     */
    public Float getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.market_price
     *
     * @param marketPrice the value for cart.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(Float marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goods_price
     *
     * @return the value of cart.goods_price
     *
     * @mbggenerated
     */
    public Float getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goods_price
     *
     * @param goodsPrice the value for cart.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Float goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goods_format
     *
     * @return the value of cart.goods_format
     *
     * @mbggenerated
     */
    public String getGoodsFormat() {
        return goodsFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goods_format
     *
     * @param goodsFormat the value for cart.goods_format
     *
     * @mbggenerated
     */
    public void setGoodsFormat(String goodsFormat) {
        this.goodsFormat = goodsFormat == null ? null : goodsFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goods_number
     *
     * @return the value of cart.goods_number
     *
     * @mbggenerated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goods_number
     *
     * @param goodsNumber the value for cart.goods_number
     *
     * @mbggenerated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.rec_type
     *
     * @return the value of cart.rec_type
     *
     * @mbggenerated
     */
    public Byte getRecType() {
        return recType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.rec_type
     *
     * @param recType the value for cart.rec_type
     *
     * @mbggenerated
     */
    public void setRecType(Byte recType) {
        this.recType = recType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.is_gift
     *
     * @return the value of cart.is_gift
     *
     * @mbggenerated
     */
    public Short getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.is_gift
     *
     * @param isGift the value for cart.is_gift
     *
     * @mbggenerated
     */
    public void setIsGift(Short isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.add_time
     *
     * @return the value of cart.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.add_time
     *
     * @param addTime the value for cart.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}