package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;

import javax.persistence.Id;
import java.util.Date;

public class Coupon extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_sn
     *
     * @mbggenerated
     */
    private String couponSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_type
     *
     * @mbggenerated
     */
    private Byte couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_name
     *
     * @mbggenerated
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.apply_platform
     *
     * @mbggenerated
     */
    private Byte applyPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.total_count
     *
     * @mbggenerated
     */
    private Integer totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.received_count
     *
     * @mbggenerated
     */
    private Integer receivedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.used_count
     *
     * @mbggenerated
     */
    private Integer usedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.face_value
     *
     * @mbggenerated
     */
    private Long faceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.limited_count
     *
     * @mbggenerated
     */
    private Byte limitedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.apply_channel
     *
     * @mbggenerated
     */
    private Byte applyChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.discount_value
     *
     * @mbggenerated
     */
    private Long discountValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.expiry_start_date
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd")
    private Date expiryStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.expiry_end_date
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd")
    private Date expiryEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.valid_days
     *
     * @mbggenerated
     */
    private Integer validDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.apply_goods
     *
     * @mbggenerated
     */
    private Byte applyGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_status
     *
     * @mbggenerated
     */
    private Byte couponStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.add_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.activated_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date activatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.add_user
     *
     * @mbggenerated
     */
    private String addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.activated_user
     *
     * @mbggenerated
     */
    private String activatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.id
     *
     * @return the value of coupon.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.id
     *
     * @param id the value for coupon.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_sn
     *
     * @return the value of coupon.coupon_sn
     *
     * @mbggenerated
     */
    public String getCouponSn() {
        return couponSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_sn
     *
     * @param couponSn the value for coupon.coupon_sn
     *
     * @mbggenerated
     */
    public void setCouponSn(String couponSn) {
        this.couponSn = couponSn == null ? null : couponSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_type
     *
     * @return the value of coupon.coupon_type
     *
     * @mbggenerated
     */
    public Byte getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_type
     *
     * @param couponType the value for coupon.coupon_type
     *
     * @mbggenerated
     */
    public void setCouponType(Byte couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_name
     *
     * @return the value of coupon.coupon_name
     *
     * @mbggenerated
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_name
     *
     * @param couponName the value for coupon.coupon_name
     *
     * @mbggenerated
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.apply_platform
     *
     * @return the value of coupon.apply_platform
     *
     * @mbggenerated
     */
    public Byte getApplyPlatform() {
        return applyPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.apply_platform
     *
     * @param applyPlatform the value for coupon.apply_platform
     *
     * @mbggenerated
     */
    public void setApplyPlatform(Byte applyPlatform) {
        this.applyPlatform = applyPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.total_count
     *
     * @return the value of coupon.total_count
     *
     * @mbggenerated
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.total_count
     *
     * @param totalCount the value for coupon.total_count
     *
     * @mbggenerated
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.received_count
     *
     * @return the value of coupon.received_count
     *
     * @mbggenerated
     */
    public Integer getReceivedCount() {
        return receivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.received_count
     *
     * @param receivedCount the value for coupon.received_count
     *
     * @mbggenerated
     */
    public void setReceivedCount(Integer receivedCount) {
        this.receivedCount = receivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.used_count
     *
     * @return the value of coupon.used_count
     *
     * @mbggenerated
     */
    public Integer getUsedCount() {
        return usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.used_count
     *
     * @param usedCount the value for coupon.used_count
     *
     * @mbggenerated
     */
    public void setUsedCount(Integer usedCount) {
        this.usedCount = usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.face_value
     *
     * @return the value of coupon.face_value
     *
     * @mbggenerated
     */
    public Long getFaceValue() {
        return faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.face_value
     *
     * @param faceValue the value for coupon.face_value
     *
     * @mbggenerated
     */
    public void setFaceValue(Long faceValue) {
        this.faceValue = faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.limited_count
     *
     * @return the value of coupon.limited_count
     *
     * @mbggenerated
     */
    public Byte getLimitedCount() {
        return limitedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.limited_count
     *
     * @param limitedCount the value for coupon.limited_count
     *
     * @mbggenerated
     */
    public void setLimitedCount(Byte limitedCount) {
        this.limitedCount = limitedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.apply_channel
     *
     * @return the value of coupon.apply_channel
     *
     * @mbggenerated
     */
    public Byte getApplyChannel() {
        return applyChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.apply_channel
     *
     * @param applyChannel the value for coupon.apply_channel
     *
     * @mbggenerated
     */
    public void setApplyChannel(Byte applyChannel) {
        this.applyChannel = applyChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.discount_value
     *
     * @return the value of coupon.discount_value
     *
     * @mbggenerated
     */
    public Long getDiscountValue() {
        return discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.discount_value
     *
     * @param discountValue the value for coupon.discount_value
     *
     * @mbggenerated
     */
    public void setDiscountValue(Long discountValue) {
        this.discountValue = discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.expiry_start_date
     *
     * @return the value of coupon.expiry_start_date
     *
     * @mbggenerated
     */
    public Date getExpiryStartDate() {
        return expiryStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.expiry_start_date
     *
     * @param expiryStartDate the value for coupon.expiry_start_date
     *
     * @mbggenerated
     */
    public void setExpiryStartDate(Date expiryStartDate) {
        this.expiryStartDate = expiryStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.expiry_end_date
     *
     * @return the value of coupon.expiry_end_date
     *
     * @mbggenerated
     */
    public Date getExpiryEndDate() {
        return expiryEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.expiry_end_date
     *
     * @param expiryEndDate the value for coupon.expiry_end_date
     *
     * @mbggenerated
     */
    public void setExpiryEndDate(Date expiryEndDate) {
        this.expiryEndDate = expiryEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.valid_days
     *
     * @return the value of coupon.valid_days
     *
     * @mbggenerated
     */
    public Integer getValidDays() {
        return validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.valid_days
     *
     * @param validDays the value for coupon.valid_days
     *
     * @mbggenerated
     */
    public void setValidDays(Integer validDays) {
        this.validDays = validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.apply_goods
     *
     * @return the value of coupon.apply_goods
     *
     * @mbggenerated
     */
    public Byte getApplyGoods() {
        return applyGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.apply_goods
     *
     * @param applyGoods the value for coupon.apply_goods
     *
     * @mbggenerated
     */
    public void setApplyGoods(Byte applyGoods) {
        this.applyGoods = applyGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_status
     *
     * @return the value of coupon.coupon_status
     *
     * @mbggenerated
     */
    public Byte getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_status
     *
     * @param couponStatus the value for coupon.coupon_status
     *
     * @mbggenerated
     */
    public void setCouponStatus(Byte couponStatus) {
        this.couponStatus = couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.add_time
     *
     * @return the value of coupon.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.add_time
     *
     * @param addTime the value for coupon.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.activated_time
     *
     * @return the value of coupon.activated_time
     *
     * @mbggenerated
     */
    public Date getActivatedTime() {
        return activatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.activated_time
     *
     * @param activatedTime the value for coupon.activated_time
     *
     * @mbggenerated
     */
    public void setActivatedTime(Date activatedTime) {
        this.activatedTime = activatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.update_time
     *
     * @return the value of coupon.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.update_time
     *
     * @param updateTime the value for coupon.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.user_name
     *
     * @return the value of coupon.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.user_name
     *
     * @param userName the value for coupon.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.add_user
     *
     * @return the value of coupon.add_user
     *
     * @mbggenerated
     */
    public String getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.add_user
     *
     * @param addUser the value for coupon.add_user
     *
     * @mbggenerated
     */
    public void setAddUser(String addUser) {
        this.addUser = addUser == null ? null : addUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.activated_user
     *
     * @return the value of coupon.activated_user
     *
     * @mbggenerated
     */
    public String getActivatedUser() {
        return activatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.activated_user
     *
     * @param activatedUser the value for coupon.activated_user
     *
     * @mbggenerated
     */
    public void setActivatedUser(String activatedUser) {
        this.activatedUser = activatedUser == null ? null : activatedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.update_user
     *
     * @return the value of coupon.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.update_user
     *
     * @param updateUser the value for coupon.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.is_deleted
     *
     * @return the value of coupon.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.is_deleted
     *
     * @param isDeleted the value for coupon.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}