package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;
import java.util.Date;

public class GeneralCodes extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.property
     *
     * @mbggenerated
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.describle
     *
     * @mbggenerated
     */
    private String describle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.is_vaild
     *
     * @mbggenerated
     */
    private Byte isVaild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_codes.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.id
     *
     * @return the value of general_codes.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.id
     *
     * @param id the value for general_codes.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.code
     *
     * @return the value of general_codes.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.code
     *
     * @param code the value for general_codes.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.property
     *
     * @return the value of general_codes.property
     *
     * @mbggenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.property
     *
     * @param property the value for general_codes.property
     *
     * @mbggenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.describle
     *
     * @return the value of general_codes.describle
     *
     * @mbggenerated
     */
    public String getDescrible() {
        return describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.describle
     *
     * @param describle the value for general_codes.describle
     *
     * @mbggenerated
     */
    public void setDescrible(String describle) {
        this.describle = describle == null ? null : describle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.remark
     *
     * @return the value of general_codes.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.remark
     *
     * @param remark the value for general_codes.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.seq
     *
     * @return the value of general_codes.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.seq
     *
     * @param seq the value for general_codes.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.is_vaild
     *
     * @return the value of general_codes.is_vaild
     *
     * @mbggenerated
     */
    public Byte getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.is_vaild
     *
     * @param isVaild the value for general_codes.is_vaild
     *
     * @mbggenerated
     */
    public void setIsVaild(Byte isVaild) {
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.update_time
     *
     * @return the value of general_codes.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.update_time
     *
     * @param updateTime the value for general_codes.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_codes.update_user
     *
     * @return the value of general_codes.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_codes.update_user
     *
     * @param updateUser the value for general_codes.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}