package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class GoodsCheck extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_check.id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_check.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    private String goodsSn;

    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_check.check_status
     *
     * @mbggenerated
     */
    private Byte checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_check.check_user
     *
     * @mbggenerated
     */
    private String checkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_check.check_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_check.check_content
     *
     * @mbggenerated
     */
    private String checkContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_check.id
     *
     * @return the value of goods_check.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_check.id
     *
     * @param id the value for goods_check.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_check.goods_id
     *
     * @return the value of goods_check.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_check.goods_id
     *
     * @param goodsId the value for goods_check.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_check.check_status
     *
     * @return the value of goods_check.check_status
     *
     * @mbggenerated
     */
    public Byte getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_check.check_status
     *
     * @param checkStatus the value for goods_check.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(Byte checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_check.check_user
     *
     * @return the value of goods_check.check_user
     *
     * @mbggenerated
     */
    public String getCheckUser() {
        return checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_check.check_user
     *
     * @param checkUser the value for goods_check.check_user
     *
     * @mbggenerated
     */
    public void setCheckUser(String checkUser) {
        this.checkUser = checkUser == null ? null : checkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_check.check_time
     *
     * @return the value of goods_check.check_time
     *
     * @mbggenerated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_check.check_time
     *
     * @param checkTime the value for goods_check.check_time
     *
     * @mbggenerated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_check.check_content
     *
     * @return the value of goods_check.check_content
     *
     * @mbggenerated
     */
    public String getCheckContent() {
        return checkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_check.check_content
     *
     * @param checkContent the value for goods_check.check_content
     *
     * @mbggenerated
     */
    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent == null ? null : checkContent.trim();
    }

    public String getGoodsSn() {
        return goodsSn;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }
}