package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;
import java.util.Date;

public class GoodsShelves extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.shelves_id
     *
     * @mbggenerated
     */
    private String shelvesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.shelves_name
     *
     * @mbggenerated
     */
    private String shelvesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.domain_id
     *
     * @mbggenerated
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shelves.add_user
     *
     * @mbggenerated
     */
    private String addUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.shelves_id
     *
     * @return the value of goods_shelves.shelves_id
     *
     * @mbggenerated
     */
    public String getShelvesId() {
        return shelvesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.shelves_id
     *
     * @param shelvesId the value for goods_shelves.shelves_id
     *
     * @mbggenerated
     */
    public void setShelvesId(String shelvesId) {
        this.shelvesId = shelvesId == null ? null : shelvesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.shelves_name
     *
     * @return the value of goods_shelves.shelves_name
     *
     * @mbggenerated
     */
    public String getShelvesName() {
        return shelvesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.shelves_name
     *
     * @param shelvesName the value for goods_shelves.shelves_name
     *
     * @mbggenerated
     */
    public void setShelvesName(String shelvesName) {
        this.shelvesName = shelvesName == null ? null : shelvesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.domain_id
     *
     * @return the value of goods_shelves.domain_id
     *
     * @mbggenerated
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.domain_id
     *
     * @param domainId the value for goods_shelves.domain_id
     *
     * @mbggenerated
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.add_time
     *
     * @return the value of goods_shelves.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.add_time
     *
     * @param addTime the value for goods_shelves.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.last_update_time
     *
     * @return the value of goods_shelves.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.last_update_time
     *
     * @param lastUpdateTime the value for goods_shelves.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.user_id
     *
     * @return the value of goods_shelves.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.user_id
     *
     * @param userId the value for goods_shelves.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shelves.add_user
     *
     * @return the value of goods_shelves.add_user
     *
     * @mbggenerated
     */
    public String getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shelves.add_user
     *
     * @param addUser the value for goods_shelves.add_user
     *
     * @mbggenerated
     */
    public void setAddUser(String addUser) {
        this.addUser = addUser == null ? null : addUser.trim();
    }
}