package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;

import javax.persistence.Id;
import java.util.Date;

public class GoodsAttrType extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.type_id
     *
     * @mbggenerated
     */
    @Id
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.type_status
     *
     * @mbggenerated
     */
    private Byte typeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.domain_id
     *
     * @mbggenerated
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.add_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.last_update_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.is_attr
     *
     * @mbggenerated
     */
    private Byte isAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.level
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_attr_type.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.type_id
     *
     * @return the value of goods_attr_type.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.type_id
     *
     * @param typeId the value for goods_attr_type.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.type_name
     *
     * @return the value of goods_attr_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.type_name
     *
     * @param typeName the value for goods_attr_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.type_status
     *
     * @return the value of goods_attr_type.type_status
     *
     * @mbggenerated
     */
    public Byte getTypeStatus() {
        return typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.type_status
     *
     * @param typeStatus the value for goods_attr_type.type_status
     *
     * @mbggenerated
     */
    public void setTypeStatus(Byte typeStatus) {
        this.typeStatus = typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.domain_id
     *
     * @return the value of goods_attr_type.domain_id
     *
     * @mbggenerated
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.domain_id
     *
     * @param domainId the value for goods_attr_type.domain_id
     *
     * @mbggenerated
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.add_time
     *
     * @return the value of goods_attr_type.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.add_time
     *
     * @param addTime the value for goods_attr_type.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.last_update_time
     *
     * @return the value of goods_attr_type.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.last_update_time
     *
     * @param lastUpdateTime the value for goods_attr_type.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.user_id
     *
     * @return the value of goods_attr_type.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.user_id
     *
     * @param userId the value for goods_attr_type.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.is_attr
     *
     * @return the value of goods_attr_type.is_attr
     *
     * @mbggenerated
     */
    public Byte getIsAttr() {
        return isAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.is_attr
     *
     * @param isAttr the value for goods_attr_type.is_attr
     *
     * @mbggenerated
     */
    public void setIsAttr(Byte isAttr) {
        this.isAttr = isAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.parent_id
     *
     * @return the value of goods_attr_type.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.parent_id
     *
     * @param parentId the value for goods_attr_type.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.level
     *
     * @return the value of goods_attr_type.level
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.level
     *
     * @param level the value for goods_attr_type.level
     *
     * @mbggenerated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_attr_type.version
     *
     * @return the value of goods_attr_type.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_attr_type.version
     *
     * @param version the value for goods_attr_type.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}