package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;
import java.util.Date;

public class Industry extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.industry_id
     *
     * @mbggenerated
     */
    private Integer industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.industry_name
     *
     * @mbggenerated
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.parent_industry_id
     *
     * @mbggenerated
     */
    private String parentIndustryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.industry_level
     *
     * @mbggenerated
     */
    private Short industryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.boost
     *
     * @mbggenerated
     */
    private Integer boost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.opt_time
     *
     * @mbggenerated
     */
    private Date optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.abbreviation
     *
     * @mbggenerated
     */
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.sub_user
     *
     * @mbggenerated
     */
    private String subUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.industry_id
     *
     * @return the value of industry.industry_id
     *
     * @mbggenerated
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.industry_id
     *
     * @param industryId the value for industry.industry_id
     *
     * @mbggenerated
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.industry_name
     *
     * @return the value of industry.industry_name
     *
     * @mbggenerated
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.industry_name
     *
     * @param industryName the value for industry.industry_name
     *
     * @mbggenerated
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.parent_industry_id
     *
     * @return the value of industry.parent_industry_id
     *
     * @mbggenerated
     */
    public String getParentIndustryId() {
        return parentIndustryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.parent_industry_id
     *
     * @param parentIndustryId the value for industry.parent_industry_id
     *
     * @mbggenerated
     */
    public void setParentIndustryId(String parentIndustryId) {
        this.parentIndustryId = parentIndustryId == null ? null : parentIndustryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.industry_level
     *
     * @return the value of industry.industry_level
     *
     * @mbggenerated
     */
    public Short getIndustryLevel() {
        return industryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.industry_level
     *
     * @param industryLevel the value for industry.industry_level
     *
     * @mbggenerated
     */
    public void setIndustryLevel(Short industryLevel) {
        this.industryLevel = industryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.boost
     *
     * @return the value of industry.boost
     *
     * @mbggenerated
     */
    public Integer getBoost() {
        return boost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.boost
     *
     * @param boost the value for industry.boost
     *
     * @mbggenerated
     */
    public void setBoost(Integer boost) {
        this.boost = boost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.opt_time
     *
     * @return the value of industry.opt_time
     *
     * @mbggenerated
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.opt_time
     *
     * @param optTime the value for industry.opt_time
     *
     * @mbggenerated
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.abbreviation
     *
     * @return the value of industry.abbreviation
     *
     * @mbggenerated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.abbreviation
     *
     * @param abbreviation the value for industry.abbreviation
     *
     * @mbggenerated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.sub_user
     *
     * @return the value of industry.sub_user
     *
     * @mbggenerated
     */
    public String getSubUser() {
        return subUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.sub_user
     *
     * @param subUser the value for industry.sub_user
     *
     * @mbggenerated
     */
    public void setSubUser(String subUser) {
        this.subUser = subUser == null ? null : subUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.add_time
     *
     * @return the value of industry.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.add_time
     *
     * @param addTime the value for industry.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.version
     *
     * @return the value of industry.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.version
     *
     * @param version the value for industry.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}