package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class Invoice extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_addr_id
     *
     * @mbggenerated
     */
    private String invoiceAddrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_sn
     *
     * @mbggenerated
     */
    private String invoiceSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_type
     *
     * @mbggenerated
     */
    private Byte invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_medium
     *
     * @mbggenerated
     */
    private Byte invoiceMedium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_content
     *
     * @mbggenerated
     */
    private String invoiceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_amount
     *
     * @mbggenerated
     */
    private Long invoiceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_title
     *
     * @mbggenerated
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.taxpayer_identification_no
     *
     * @mbggenerated
     */
    private String taxpayerIdentificationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.reg_address
     *
     * @mbggenerated
     */
    private String regAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.reg_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.open_bank
     *
     * @mbggenerated
     */
    private String openBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.bank_account
     *
     * @mbggenerated
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_status
     *
     * @mbggenerated
     */
    private Byte invoiceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.order_id
     *
     * @mbggenerated
     */
    private String auditOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_change
     *
     * @mbggenerated
     */
    private Byte invoiceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.add_user
     *
     * @mbggenerated
     */
    private String addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.add_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_id
     *
     * @return the value of invoice.invoice_id
     *
     * @mbggenerated
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_id
     *
     * @param invoiceId the value for invoice.invoice_id
     *
     * @mbggenerated
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_addr_id
     *
     * @return the value of invoice.invoice_addr_id
     *
     * @mbggenerated
     */
    public String getInvoiceAddrId() {
        return invoiceAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_addr_id
     *
     * @param invoiceAddrId the value for invoice.invoice_addr_id
     *
     * @mbggenerated
     */
    public void setInvoiceAddrId(String invoiceAddrId) {
        this.invoiceAddrId = invoiceAddrId == null ? null : invoiceAddrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_sn
     *
     * @return the value of invoice.invoice_sn
     *
     * @mbggenerated
     */
    public String getInvoiceSn() {
        return invoiceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_sn
     *
     * @param invoiceSn the value for invoice.invoice_sn
     *
     * @mbggenerated
     */
    public void setInvoiceSn(String invoiceSn) {
        this.invoiceSn = invoiceSn == null ? null : invoiceSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_type
     *
     * @return the value of invoice.invoice_type
     *
     * @mbggenerated
     */
    public Byte getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_type
     *
     * @param invoiceType the value for invoice.invoice_type
     *
     * @mbggenerated
     */
    public void setInvoiceType(Byte invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_medium
     *
     * @return the value of invoice.invoice_medium
     *
     * @mbggenerated
     */
    public Byte getInvoiceMedium() {
        return invoiceMedium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_medium
     *
     * @param invoiceMedium the value for invoice.invoice_medium
     *
     * @mbggenerated
     */
    public void setInvoiceMedium(Byte invoiceMedium) {
        this.invoiceMedium = invoiceMedium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_content
     *
     * @return the value of invoice.invoice_content
     *
     * @mbggenerated
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_content
     *
     * @param invoiceContent the value for invoice.invoice_content
     *
     * @mbggenerated
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_amount
     *
     * @return the value of invoice.invoice_amount
     *
     * @mbggenerated
     */
    public Long getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_amount
     *
     * @param invoiceAmount the value for invoice.invoice_amount
     *
     * @mbggenerated
     */
    public void setInvoiceAmount(Long invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_title
     *
     * @return the value of invoice.invoice_title
     *
     * @mbggenerated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_title
     *
     * @param invoiceTitle the value for invoice.invoice_title
     *
     * @mbggenerated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.taxpayer_identification_no
     *
     * @return the value of invoice.taxpayer_identification_no
     *
     * @mbggenerated
     */
    public String getTaxpayerIdentificationNo() {
        return taxpayerIdentificationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.taxpayer_identification_no
     *
     * @param taxpayerIdentificationNo the value for invoice.taxpayer_identification_no
     *
     * @mbggenerated
     */
    public void setTaxpayerIdentificationNo(String taxpayerIdentificationNo) {
        this.taxpayerIdentificationNo = taxpayerIdentificationNo == null ? null : taxpayerIdentificationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.reg_address
     *
     * @return the value of invoice.reg_address
     *
     * @mbggenerated
     */
    public String getRegAddress() {
        return regAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.reg_address
     *
     * @param regAddress the value for invoice.reg_address
     *
     * @mbggenerated
     */
    public void setRegAddress(String regAddress) {
        this.regAddress = regAddress == null ? null : regAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.reg_time
     *
     * @return the value of invoice.reg_time
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.reg_time
     *
     * @param regTime the value for invoice.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.open_bank
     *
     * @return the value of invoice.open_bank
     *
     * @mbggenerated
     */
    public String getOpenBank() {
        return openBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.open_bank
     *
     * @param openBank the value for invoice.open_bank
     *
     * @mbggenerated
     */
    public void setOpenBank(String openBank) {
        this.openBank = openBank == null ? null : openBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.bank_account
     *
     * @return the value of invoice.bank_account
     *
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.bank_account
     *
     * @param bankAccount the value for invoice.bank_account
     *
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_status
     *
     * @return the value of invoice.invoice_status
     *
     * @mbggenerated
     */
    public Byte getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_status
     *
     * @param invoiceStatus the value for invoice.invoice_status
     *
     * @mbggenerated
     */
    public void setInvoiceStatus(Byte invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.audit_opinion
     *
     * @return the value of invoice.audit_opinion
     *
     * @mbggenerated
     */
    public String getAuditOpinion() {
        return auditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.audit_opinion
     *
     * @param auditOpinion the value for invoice.audit_opinion
     *
     * @mbggenerated
     */
    public void setAuditOpinion(String auditOpinion) {
        this.auditOpinion = auditOpinion == null ? null : auditOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_change
     *
     * @return the value of invoice.invoice_change
     *
     * @mbggenerated
     */
    public Byte getInvoiceChange() {
        return invoiceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_change
     *
     * @param invoiceChange the value for invoice.invoice_change
     *
     * @mbggenerated
     */
    public void setInvoiceChange(Byte invoiceChange) {
        this.invoiceChange = invoiceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.add_user
     *
     * @return the value of invoice.add_user
     *
     * @mbggenerated
     */
    public String getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.add_user
     *
     * @param addUser the value for invoice.add_user
     *
     * @mbggenerated
     */
    public void setAddUser(String addUser) {
        this.addUser = addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.add_time
     *
     * @return the value of invoice.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.add_time
     *
     * @param addTime the value for invoice.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.version
     *
     * @return the value of invoice.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.version
     *
     * @param version the value for invoice.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}