package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;
import java.util.Date;

public class MessageTemplate extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.event_type
     *
     * @mbggenerated
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template_header
     *
     * @mbggenerated
     */
    private String templateHeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template_content
     *
     * @mbggenerated
     */
    private String templateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template_type
     *
     * @mbggenerated
     */
    private Byte templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.is_vaild
     *
     * @mbggenerated
     */
    private Byte isVaild;

    private String smsTypeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.id
     *
     * @return the value of message_template.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.id
     *
     * @param id the value for message_template.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.event_type
     *
     * @return the value of message_template.event_type
     *
     * @mbggenerated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.event_type
     *
     * @param eventType the value for message_template.event_type
     *
     * @mbggenerated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template_header
     *
     * @return the value of message_template.template_header
     *
     * @mbggenerated
     */
    public String getTemplateHeader() {
        return templateHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template_header
     *
     * @param templateHeader the value for message_template.template_header
     *
     * @mbggenerated
     */
    public void setTemplateHeader(String templateHeader) {
        this.templateHeader = templateHeader == null ? null : templateHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template_content
     *
     * @return the value of message_template.template_content
     *
     * @mbggenerated
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template_content
     *
     * @param templateContent the value for message_template.template_content
     *
     * @mbggenerated
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.update_time
     *
     * @return the value of message_template.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.update_time
     *
     * @param updateTime the value for message_template.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.update_user
     *
     * @return the value of message_template.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.update_user
     *
     * @param updateUser the value for message_template.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template_type
     *
     * @return the value of message_template.template_type
     *
     * @mbggenerated
     */
    public Byte getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template_type
     *
     * @param templateType the value for message_template.template_type
     *
     * @mbggenerated
     */
    public void setTemplateType(Byte templateType) {
        this.templateType = templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.is_vaild
     *
     * @return the value of message_template.is_vaild
     *
     * @mbggenerated
     */
    public Byte getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.is_vaild
     *
     * @param isVaild the value for message_template.is_vaild
     *
     * @mbggenerated
     */
    public void setIsVaild(Byte isVaild) {
        this.isVaild = isVaild;
    }

    public String getSmsTypeCode() {
        return smsTypeCode;
    }

    public void setSmsTypeCode(String smsTypeCode) {
        this.smsTypeCode = smsTypeCode;
    }
}