package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;

import javax.persistence.Id;
import java.util.Date;

public class OauthClient extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_id
     *
     * @mbggenerated
     */
    @Id
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_secret
     *
     * @mbggenerated
     */
    private String clientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_name
     *
     * @mbggenerated
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_uri
     *
     * @mbggenerated
     */
    private String clientUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.client_icon_uri
     *
     * @mbggenerated
     */
    private String clientIconUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.resource_ids
     *
     * @mbggenerated
     */
    private String resourceIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.grant_types
     *
     * @mbggenerated
     */
    private String grantTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.redirect_uri
     *
     * @mbggenerated
     */
    private String redirectUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.access_token_validity
     *
     * @mbggenerated
     */
    private Integer accessTokenValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.refresh_token_validity
     *
     * @mbggenerated
     */
    private Integer refreshTokenValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.archived
     *
     * @mbggenerated
     */
    private Byte archived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client.trusted
     *
     * @mbggenerated
     */
    private Byte trusted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_id
     *
     * @return the value of oauth_client.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_id
     *
     * @param clientId the value for oauth_client.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_secret
     *
     * @return the value of oauth_client.client_secret
     *
     * @mbggenerated
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_secret
     *
     * @param clientSecret the value for oauth_client.client_secret
     *
     * @mbggenerated
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_name
     *
     * @return the value of oauth_client.client_name
     *
     * @mbggenerated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_name
     *
     * @param clientName the value for oauth_client.client_name
     *
     * @mbggenerated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_uri
     *
     * @return the value of oauth_client.client_uri
     *
     * @mbggenerated
     */
    public String getClientUri() {
        return clientUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_uri
     *
     * @param clientUri the value for oauth_client.client_uri
     *
     * @mbggenerated
     */
    public void setClientUri(String clientUri) {
        this.clientUri = clientUri == null ? null : clientUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.client_icon_uri
     *
     * @return the value of oauth_client.client_icon_uri
     *
     * @mbggenerated
     */
    public String getClientIconUri() {
        return clientIconUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.client_icon_uri
     *
     * @param clientIconUri the value for oauth_client.client_icon_uri
     *
     * @mbggenerated
     */
    public void setClientIconUri(String clientIconUri) {
        this.clientIconUri = clientIconUri == null ? null : clientIconUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.resource_ids
     *
     * @return the value of oauth_client.resource_ids
     *
     * @mbggenerated
     */
    public String getResourceIds() {
        return resourceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.resource_ids
     *
     * @param resourceIds the value for oauth_client.resource_ids
     *
     * @mbggenerated
     */
    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds == null ? null : resourceIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.scope
     *
     * @return the value of oauth_client.scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.scope
     *
     * @param scope the value for oauth_client.scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.grant_types
     *
     * @return the value of oauth_client.grant_types
     *
     * @mbggenerated
     */
    public String getGrantTypes() {
        return grantTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.grant_types
     *
     * @param grantTypes the value for oauth_client.grant_types
     *
     * @mbggenerated
     */
    public void setGrantTypes(String grantTypes) {
        this.grantTypes = grantTypes == null ? null : grantTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.redirect_uri
     *
     * @return the value of oauth_client.redirect_uri
     *
     * @mbggenerated
     */
    public String getRedirectUri() {
        return redirectUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.redirect_uri
     *
     * @param redirectUri the value for oauth_client.redirect_uri
     *
     * @mbggenerated
     */
    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri == null ? null : redirectUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.role
     *
     * @return the value of oauth_client.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.role
     *
     * @param role the value for oauth_client.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.access_token_validity
     *
     * @return the value of oauth_client.access_token_validity
     *
     * @mbggenerated
     */
    public Integer getAccessTokenValidity() {
        return accessTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.access_token_validity
     *
     * @param accessTokenValidity the value for oauth_client.access_token_validity
     *
     * @mbggenerated
     */
    public void setAccessTokenValidity(Integer accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.refresh_token_validity
     *
     * @return the value of oauth_client.refresh_token_validity
     *
     * @mbggenerated
     */
    public Integer getRefreshTokenValidity() {
        return refreshTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.refresh_token_validity
     *
     * @param refreshTokenValidity the value for oauth_client.refresh_token_validity
     *
     * @mbggenerated
     */
    public void setRefreshTokenValidity(Integer refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.description
     *
     * @return the value of oauth_client.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.description
     *
     * @param description the value for oauth_client.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.create_time
     *
     * @return the value of oauth_client.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.create_time
     *
     * @param createTime the value for oauth_client.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.archived
     *
     * @return the value of oauth_client.archived
     *
     * @mbggenerated
     */
    public Byte getArchived() {
        return archived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.archived
     *
     * @param archived the value for oauth_client.archived
     *
     * @mbggenerated
     */
    public void setArchived(Byte archived) {
        this.archived = archived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client.trusted
     *
     * @return the value of oauth_client.trusted
     *
     * @mbggenerated
     */
    public Byte getTrusted() {
        return trusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client.trusted
     *
     * @param trusted the value for oauth_client.trusted
     *
     * @mbggenerated
     */
    public void setTrusted(Byte trusted) {
        this.trusted = trusted;
    }
}