package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class PayAccountRecord extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.pay_account_id
     *
     * @mbggenerated
     */
    private Long payAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.money
     *
     * @mbggenerated
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_type
     *
     * @mbggenerated
     */
    private Byte transferType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.pay_bank_card_id
     *
     * @mbggenerated
     */
    private Integer payBankCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_status
     *
     * @mbggenerated
     */
    private Byte transferStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.sqbh_number
     *
     * @mbggenerated
     */
    private String sqbhNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.channel_type
     *
     * @mbggenerated
     */
    private String channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd")
    private Date transferDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.add_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.add_operator
     *
     * @mbggenerated
     */
    private String addOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.update_operator
     *
     * @mbggenerated
     */
    private String updateOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_code
     *
     * @mbggenerated
     */
    private String transferCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_Message
     *
     * @mbggenerated
     */
    private String transferMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_result
     *
     * @mbggenerated
     */
    private String transferResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_desc
     *
     * @mbggenerated
     */
    private String transferDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.send_msg
     *
     * @mbggenerated
     */
    private String sendMsg;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPayAccountId() {
        return payAccountId;
    }

    public void setPayAccountId(Long payAccountId) {
        this.payAccountId = payAccountId;
    }

    public String getSqbhNumber() {
        return sqbhNumber;
    }

    public void setSqbhNumber(String sqbhNumber) {
        this.sqbhNumber = sqbhNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.user_id
     *
     * @return the value of pay_account_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.user_id
     *
     * @param userId the value for pay_account_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_date
     *
     * @return the value of pay_account_record.transfer_date
     *
     * @mbggenerated
     */
    public Date getTransferDate() {
        return transferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_date
     *
     * @param transferDate the value for pay_account_record.transfer_date
     *
     * @mbggenerated
     */
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.money
     *
     * @return the value of pay_account_record.money
     *
     * @mbggenerated
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.money
     *
     * @param money the value for pay_account_record.money
     *
     * @mbggenerated
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_type
     *
     * @return the value of pay_account_record.transfer_type
     *
     * @mbggenerated
     */
    public Byte getTransferType() {
        return transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_type
     *
     * @param transferType the value for pay_account_record.transfer_type
     *
     * @mbggenerated
     */
    public void setTransferType(Byte transferType) {
        this.transferType = transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.pay_bank_card_id
     *
     * @return the value of pay_account_record.pay_bank_card_id
     *
     * @mbggenerated
     */
    public Integer getPayBankCardId() {
        return payBankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.pay_bank_card_id
     *
     * @param payBankCardId the value for pay_account_record.pay_bank_card_id
     *
     * @mbggenerated
     */
    public void setPayBankCardId(Integer payBankCardId) {
        this.payBankCardId = payBankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_status
     *
     * @return the value of pay_account_record.transfer_status
     *
     * @mbggenerated
     */
    public Byte getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_status
     *
     * @param transferStatus the value for pay_account_record.transfer_status
     *
     * @mbggenerated
     */
    public void setTransferStatus(Byte transferStatus) {
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.serial_number
     *
     * @return the value of pay_account_record.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.serial_number
     *
     * @param serialNumber the value for pay_account_record.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.channel_type
     *
     * @return the value of pay_account_record.channel_type
     *
     * @mbggenerated
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.channel_type
     *
     * @param channelType the value for pay_account_record.channel_type
     *
     * @mbggenerated
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.add_time
     *
     * @return the value of pay_account_record.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.add_time
     *
     * @param addTime the value for pay_account_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.update_time
     *
     * @return the value of pay_account_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.update_time
     *
     * @param updateTime the value for pay_account_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.add_operator
     *
     * @return the value of pay_account_record.add_operator
     *
     * @mbggenerated
     */
    public String getAddOperator() {
        return addOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.add_operator
     *
     * @param addOperator the value for pay_account_record.add_operator
     *
     * @mbggenerated
     */
    public void setAddOperator(String addOperator) {
        this.addOperator = addOperator == null ? null : addOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.update_operator
     *
     * @return the value of pay_account_record.update_operator
     *
     * @mbggenerated
     */
    public String getUpdateOperator() {
        return updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.update_operator
     *
     * @param updateOperator the value for pay_account_record.update_operator
     *
     * @mbggenerated
     */
    public void setUpdateOperator(String updateOperator) {
        this.updateOperator = updateOperator == null ? null : updateOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_code
     *
     * @return the value of pay_account_record.transfer_code
     *
     * @mbggenerated
     */
    public String getTransferCode() {
        return transferCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_code
     *
     * @param transferCode the value for pay_account_record.transfer_code
     *
     * @mbggenerated
     */
    public void setTransferCode(String transferCode) {
        this.transferCode = transferCode == null ? null : transferCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_Message
     *
     * @return the value of pay_account_record.transfer_Message
     *
     * @mbggenerated
     */
    public String getTransferMessage() {
        return transferMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_Message
     *
     * @param transferMessage the value for pay_account_record.transfer_Message
     *
     * @mbggenerated
     */
    public void setTransferMessage(String transferMessage) {
        this.transferMessage = transferMessage == null ? null : transferMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_result
     *
     * @return the value of pay_account_record.transfer_result
     *
     * @mbggenerated
     */
    public String getTransferResult() {
        return transferResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_result
     *
     * @param transferResult the value for pay_account_record.transfer_result
     *
     * @mbggenerated
     */
    public void setTransferResult(String transferResult) {
        this.transferResult = transferResult == null ? null : transferResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_desc
     *
     * @return the value of pay_account_record.transfer_desc
     *
     * @mbggenerated
     */
    public String getTransferDesc() {
        return transferDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_desc
     *
     * @param transferDesc the value for pay_account_record.transfer_desc
     *
     * @mbggenerated
     */
    public void setTransferDesc(String transferDesc) {
        this.transferDesc = transferDesc == null ? null : transferDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.send_msg
     *
     * @return the value of pay_account_record.send_msg
     *
     * @mbggenerated
     */
    public String getSendMsg() {
        return sendMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.send_msg
     *
     * @param sendMsg the value for pay_account_record.send_msg
     *
     * @mbggenerated
     */
    public void setSendMsg(String sendMsg) {
        this.sendMsg = sendMsg == null ? null : sendMsg.trim();
    }
}