package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class PayAccountRecord extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.pay_account_id
     *
     * @mbggenerated
     */
    private Integer payAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.money
     *
     * @mbggenerated
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_type
     *
     * @mbggenerated
     */
    private Byte transferType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.pay_bank_card_id
     *
     * @mbggenerated
     */
    private Integer payBankCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.transfer_status
     *
     * @mbggenerated
     */
    private Byte transferStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.sqbh_number
     *
     * @mbggenerated
     */
    private Integer sqbhNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.channel_type
     *
     * @mbggenerated
     */
    private String channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.add_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.add_operator
     *
     * @mbggenerated
     */
    private String addOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account_record.update_operator
     *
     * @mbggenerated
     */
    private String updateOperator;

    private LocalDate transferDate;

    private String transferMsg;

    public String getTransferMsg() {
        return transferMsg;
    }

    public void setTransferMsg(String transferMsg) {
        this.transferMsg = transferMsg;
    }

    public LocalDate getTransferDate() {
        return transferDate;
    }

    public void setTransferDate(LocalDate transferDate) {
        this.transferDate = transferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.id
     *
     * @return the value of pay_account_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.id
     *
     * @param id the value for pay_account_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.pay_account_id
     *
     * @return the value of pay_account_record.pay_account_id
     *
     * @mbggenerated
     */
    public Integer getPayAccountId() {
        return payAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.pay_account_id
     *
     * @param payAccountId the value for pay_account_record.pay_account_id
     *
     * @mbggenerated
     */
    public void setPayAccountId(Integer payAccountId) {
        this.payAccountId = payAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.user_id
     *
     * @return the value of pay_account_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.user_id
     *
     * @param userId the value for pay_account_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.money
     *
     * @return the value of pay_account_record.money
     *
     * @mbggenerated
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.money
     *
     * @param money the value for pay_account_record.money
     *
     * @mbggenerated
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_type
     *
     * @return the value of pay_account_record.transfer_type
     *
     * @mbggenerated
     */
    public Byte getTransferType() {
        return transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_type
     *
     * @param transferType the value for pay_account_record.transfer_type
     *
     * @mbggenerated
     */
    public void setTransferType(Byte transferType) {
        this.transferType = transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.pay_bank_card_id
     *
     * @return the value of pay_account_record.pay_bank_card_id
     *
     * @mbggenerated
     */
    public Integer getPayBankCardId() {
        return payBankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.pay_bank_card_id
     *
     * @param payBankCardId the value for pay_account_record.pay_bank_card_id
     *
     * @mbggenerated
     */
    public void setPayBankCardId(Integer payBankCardId) {
        this.payBankCardId = payBankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.transfer_status
     *
     * @return the value of pay_account_record.transfer_status
     *
     * @mbggenerated
     */
    public Byte getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.transfer_status
     *
     * @param transferStatus the value for pay_account_record.transfer_status
     *
     * @mbggenerated
     */
    public void setTransferStatus(Byte transferStatus) {
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.serial_number
     *
     * @return the value of pay_account_record.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.serial_number
     *
     * @param serialNumber the value for pay_account_record.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.sqbh_number
     *
     * @return the value of pay_account_record.sqbh_number
     *
     * @mbggenerated
     */
    public Integer getSqbhNumber() {
        return sqbhNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.sqbh_number
     *
     * @param sqbhNumber the value for pay_account_record.sqbh_number
     *
     * @mbggenerated
     */
    public void setSqbhNumber(Integer sqbhNumber) {
        this.sqbhNumber = sqbhNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.channel_type
     *
     * @return the value of pay_account_record.channel_type
     *
     * @mbggenerated
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.channel_type
     *
     * @param channelType the value for pay_account_record.channel_type
     *
     * @mbggenerated
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.add_time
     *
     * @return the value of pay_account_record.add_time
     *
     * @mbggenerated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.add_time
     *
     * @param addTime the value for pay_account_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.update_time
     *
     * @return the value of pay_account_record.update_time
     *
     * @mbggenerated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.update_time
     *
     * @param updateTime the value for pay_account_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.add_operator
     *
     * @return the value of pay_account_record.add_operator
     *
     * @mbggenerated
     */
    public String getAddOperator() {
        return addOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.add_operator
     *
     * @param addOperator the value for pay_account_record.add_operator
     *
     * @mbggenerated
     */
    public void setAddOperator(String addOperator) {
        this.addOperator = addOperator == null ? null : addOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account_record.update_operator
     *
     * @return the value of pay_account_record.update_operator
     *
     * @mbggenerated
     */
    public String getUpdateOperator() {
        return updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account_record.update_operator
     *
     * @param updateOperator the value for pay_account_record.update_operator
     *
     * @mbggenerated
     */
    public void setUpdateOperator(String updateOperator) {
        this.updateOperator = updateOperator;
    }
}