package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;

import javax.persistence.Id;
import java.util.Date;

public class Payment extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_id
     *
     * @mbggenerated
     */
    @Id
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_code
     *
     * @mbggenerated
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_name
     *
     * @mbggenerated
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_fee
     *
     * @mbggenerated
     */
    private String payFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_order
     *
     * @mbggenerated
     */
    private Byte payOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.enabled
     *
     * @mbggenerated
     */
    private Byte enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.is_cod
     *
     * @mbggenerated
     */
    private Byte isCod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.is_online
     *
     * @mbggenerated
     */
    private Byte isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_id
     *
     * @return the value of payment.pay_id
     *
     * @mbggenerated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_id
     *
     * @param payId the value for payment.pay_id
     *
     * @mbggenerated
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_code
     *
     * @return the value of payment.pay_code
     *
     * @mbggenerated
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_code
     *
     * @param payCode the value for payment.pay_code
     *
     * @mbggenerated
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_name
     *
     * @return the value of payment.pay_name
     *
     * @mbggenerated
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_name
     *
     * @param payName the value for payment.pay_name
     *
     * @mbggenerated
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_fee
     *
     * @return the value of payment.pay_fee
     *
     * @mbggenerated
     */
    public String getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_fee
     *
     * @param payFee the value for payment.pay_fee
     *
     * @mbggenerated
     */
    public void setPayFee(String payFee) {
        this.payFee = payFee == null ? null : payFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_order
     *
     * @return the value of payment.pay_order
     *
     * @mbggenerated
     */
    public Byte getPayOrder() {
        return payOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_order
     *
     * @param payOrder the value for payment.pay_order
     *
     * @mbggenerated
     */
    public void setPayOrder(Byte payOrder) {
        this.payOrder = payOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.enabled
     *
     * @return the value of payment.enabled
     *
     * @mbggenerated
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.enabled
     *
     * @param enabled the value for payment.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.is_cod
     *
     * @return the value of payment.is_cod
     *
     * @mbggenerated
     */
    public Byte getIsCod() {
        return isCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.is_cod
     *
     * @param isCod the value for payment.is_cod
     *
     * @mbggenerated
     */
    public void setIsCod(Byte isCod) {
        this.isCod = isCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.is_online
     *
     * @return the value of payment.is_online
     *
     * @mbggenerated
     */
    public Byte getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.is_online
     *
     * @param isOnline the value for payment.is_online
     *
     * @mbggenerated
     */
    public void setIsOnline(Byte isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.add_time
     *
     * @return the value of payment.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.add_time
     *
     * @param addTime the value for payment.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.version
     *
     * @return the value of payment.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.version
     *
     * @param version the value for payment.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}