package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import java.util.Date;

public class SettleRecord extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.wait_settle_record_id
     *
     * @mbggenerated
     */
    private Long waitSettleRecordId;

    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.settle_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd")
    private Date settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.settle_amount
     *
     * @mbggenerated
     */
    private Long settleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.trade_center_amount
     *
     * @mbggenerated
     */
    private Long tradeCenterAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.supplier_amount
     *
     * @mbggenerated
     */
    private Long supplierAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.refund_amount
     *
     * @mbggenerated
     */
    private Long refundAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.settle_status
     *
     * @mbggenerated
     */
    private Byte settleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_record.add_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    private String addOperator;

    public String getAddOperator() {
        return addOperator;
    }

    public void setAddOperator(String addOperator) {
        this.addOperator = addOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.id
     *
     * @return the value of settle_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.id
     *
     * @param id the value for settle_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.wait_settle_record_id
     *
     * @return the value of settle_record.wait_settle_record_id
     *
     * @mbggenerated
     */
    public Long getWaitSettleRecordId() {
        return waitSettleRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.wait_settle_record_id
     *
     * @param waitSettleRecordId the value for settle_record.wait_settle_record_id
     *
     * @mbggenerated
     */
    public void setWaitSettleRecordId(Long waitSettleRecordId) {
        this.waitSettleRecordId = waitSettleRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.settle_date
     *
     * @return the value of settle_record.settle_date
     *
     * @mbggenerated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.settle_date
     *
     * @param settleDate the value for settle_record.settle_date
     *
     * @mbggenerated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.settle_amount
     *
     * @return the value of settle_record.settle_amount
     *
     * @mbggenerated
     */
    public Long getSettleAmount() {
        return settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.settle_amount
     *
     * @param settleAmount the value for settle_record.settle_amount
     *
     * @mbggenerated
     */
    public void setSettleAmount(Long settleAmount) {
        this.settleAmount = settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.trade_center_amount
     *
     * @return the value of settle_record.trade_center_amount
     *
     * @mbggenerated
     */
    public Long getTradeCenterAmount() {
        return tradeCenterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.trade_center_amount
     *
     * @param tradeCenterAmount the value for settle_record.trade_center_amount
     *
     * @mbggenerated
     */
    public void setTradeCenterAmount(Long tradeCenterAmount) {
        this.tradeCenterAmount = tradeCenterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.supplier_amount
     *
     * @return the value of settle_record.supplier_amount
     *
     * @mbggenerated
     */
    public Long getSupplierAmount() {
        return supplierAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.supplier_amount
     *
     * @param supplierAmount the value for settle_record.supplier_amount
     *
     * @mbggenerated
     */
    public void setSupplierAmount(Long supplierAmount) {
        this.supplierAmount = supplierAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.refund_amount
     *
     * @return the value of settle_record.refund_amount
     *
     * @mbggenerated
     */
    public Long getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.refund_amount
     *
     * @param refundAmount the value for settle_record.refund_amount
     *
     * @mbggenerated
     */
    public void setRefundAmount(Long refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.settle_status
     *
     * @return the value of settle_record.settle_status
     *
     * @mbggenerated
     */
    public Byte getSettleStatus() {
        return settleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.settle_status
     *
     * @param settleStatus the value for settle_record.settle_status
     *
     * @mbggenerated
     */
    public void setSettleStatus(Byte settleStatus) {
        this.settleStatus = settleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_record.add_time
     *
     * @return the value of settle_record.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_record.add_time
     *
     * @param addTime the value for settle_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }
}