package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;

public class Shop extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_id
     *
     * @mbggenerated
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_id
     *
     * @return the value of shop.shop_id
     *
     * @mbggenerated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_id
     *
     * @param shopId the value for shop.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_name
     *
     * @return the value of shop.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_name
     *
     * @param shopName the value for shop.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }
}