package com.jusfoun.hookah.core.domain;

import com.jusfoun.hookah.core.generic.GenericModel;

public class SysRoleGroup extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_group.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_group.sys_role_id
     *
     * @mbggenerated
     */
    private String sysRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_group.sys_group_id
     *
     * @mbggenerated
     */
    private String sysGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_group.id
     *
     * @return the value of sys_role_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_group.id
     *
     * @param id the value for sys_role_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_group.sys_role_id
     *
     * @return the value of sys_role_group.sys_role_id
     *
     * @mbggenerated
     */
    public String getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_group.sys_role_id
     *
     * @param sysRoleId the value for sys_role_group.sys_role_id
     *
     * @mbggenerated
     */
    public void setSysRoleId(String sysRoleId) {
        this.sysRoleId = sysRoleId == null ? null : sysRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_group.sys_group_id
     *
     * @return the value of sys_role_group.sys_group_id
     *
     * @mbggenerated
     */
    public String getSysGroupId() {
        return sysGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_group.sys_group_id
     *
     * @param sysGroupId the value for sys_role_group.sys_group_id
     *
     * @mbggenerated
     */
    public void setSysGroupId(String sysGroupId) {
        this.sysGroupId = sysGroupId == null ? null : sysGroupId.trim();
    }
}