package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;

import javax.persistence.Id;
import java.util.Date;

public class TransactionAnalysis extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.data_source
     *
     * @mbggenerated
     */
    private String dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.effective_order_amount
     *
     * @mbggenerated
     */
    private Long effectiveOrderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.effectice_order_num
     *
     * @mbggenerated
     */
    private Integer effecticeOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.comment_num
     *
     * @mbggenerated
     */
    private Integer commentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.average_pay_time
     *
     * @mbggenerated
     */
    private String averagePayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.pay_user_num
     *
     * @mbggenerated
     */
    private Integer payUserNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.order_user_num
     *
     * @mbggenerated
     */
    private Integer orderUserNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.cancel_order_num
     *
     * @mbggenerated
     */
    private Integer cancelOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.goods_sold_num
     *
     * @mbggenerated
     */
    private Integer goodsSoldNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.paying_order_num
     *
     * @mbggenerated
     */
    private Integer payingOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.add_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.add_operator
     *
     * @mbggenerated
     */
    private String addOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.update_operator
     *
     * @mbggenerated
     */
    private String updateOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_analysis.insert_time
     *
     * @mbggenerated
     */
    private String insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.id
     *
     * @return the value of transaction_analysis.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.id
     *
     * @param id the value for transaction_analysis.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.data_source
     *
     * @return the value of transaction_analysis.data_source
     *
     * @mbggenerated
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.data_source
     *
     * @param dataSource the value for transaction_analysis.data_source
     *
     * @mbggenerated
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.order_num
     *
     * @return the value of transaction_analysis.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.order_num
     *
     * @param orderNum the value for transaction_analysis.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.effective_order_amount
     *
     * @return the value of transaction_analysis.effective_order_amount
     *
     * @mbggenerated
     */
    public Long getEffectiveOrderAmount() {
        return effectiveOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.effective_order_amount
     *
     * @param effectiveOrderAmount the value for transaction_analysis.effective_order_amount
     *
     * @mbggenerated
     */
    public void setEffectiveOrderAmount(Long effectiveOrderAmount) {
        this.effectiveOrderAmount = effectiveOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.effectice_order_num
     *
     * @return the value of transaction_analysis.effectice_order_num
     *
     * @mbggenerated
     */
    public Integer getEffecticeOrderNum() {
        return effecticeOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.effectice_order_num
     *
     * @param effecticeOrderNum the value for transaction_analysis.effectice_order_num
     *
     * @mbggenerated
     */
    public void setEffecticeOrderNum(Integer effecticeOrderNum) {
        this.effecticeOrderNum = effecticeOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.comment_num
     *
     * @return the value of transaction_analysis.comment_num
     *
     * @mbggenerated
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.comment_num
     *
     * @param commentNum the value for transaction_analysis.comment_num
     *
     * @mbggenerated
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.average_pay_time
     *
     * @return the value of transaction_analysis.average_pay_time
     *
     * @mbggenerated
     */
    public String getAveragePayTime() {
        return averagePayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.average_pay_time
     *
     * @param averagePayTime the value for transaction_analysis.average_pay_time
     *
     * @mbggenerated
     */
    public void setAveragePayTime(String averagePayTime) {
        this.averagePayTime = averagePayTime == null ? null : averagePayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.pay_user_num
     *
     * @return the value of transaction_analysis.pay_user_num
     *
     * @mbggenerated
     */
    public Integer getPayUserNum() {
        return payUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.pay_user_num
     *
     * @param payUserNum the value for transaction_analysis.pay_user_num
     *
     * @mbggenerated
     */
    public void setPayUserNum(Integer payUserNum) {
        this.payUserNum = payUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.order_user_num
     *
     * @return the value of transaction_analysis.order_user_num
     *
     * @mbggenerated
     */
    public Integer getOrderUserNum() {
        return orderUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.order_user_num
     *
     * @param orderUserNum the value for transaction_analysis.order_user_num
     *
     * @mbggenerated
     */
    public void setOrderUserNum(Integer orderUserNum) {
        this.orderUserNum = orderUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.cancel_order_num
     *
     * @return the value of transaction_analysis.cancel_order_num
     *
     * @mbggenerated
     */
    public Integer getCancelOrderNum() {
        return cancelOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.cancel_order_num
     *
     * @param cancelOrderNum the value for transaction_analysis.cancel_order_num
     *
     * @mbggenerated
     */
    public void setCancelOrderNum(Integer cancelOrderNum) {
        this.cancelOrderNum = cancelOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.goods_sold_num
     *
     * @return the value of transaction_analysis.goods_sold_num
     *
     * @mbggenerated
     */
    public Integer getGoodsSoldNum() {
        return goodsSoldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.goods_sold_num
     *
     * @param goodsSoldNum the value for transaction_analysis.goods_sold_num
     *
     * @mbggenerated
     */
    public void setGoodsSoldNum(Integer goodsSoldNum) {
        this.goodsSoldNum = goodsSoldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.paying_order_num
     *
     * @return the value of transaction_analysis.paying_order_num
     *
     * @mbggenerated
     */
    public Integer getPayingOrderNum() {
        return payingOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.paying_order_num
     *
     * @param payingOrderNum the value for transaction_analysis.paying_order_num
     *
     * @mbggenerated
     */
    public void setPayingOrderNum(Integer payingOrderNum) {
        this.payingOrderNum = payingOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.add_time
     *
     * @return the value of transaction_analysis.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.add_time
     *
     * @param addTime the value for transaction_analysis.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.update_time
     *
     * @return the value of transaction_analysis.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.update_time
     *
     * @param updateTime the value for transaction_analysis.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.add_operator
     *
     * @return the value of transaction_analysis.add_operator
     *
     * @mbggenerated
     */
    public String getAddOperator() {
        return addOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.add_operator
     *
     * @param addOperator the value for transaction_analysis.add_operator
     *
     * @mbggenerated
     */
    public void setAddOperator(String addOperator) {
        this.addOperator = addOperator == null ? null : addOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.update_operator
     *
     * @return the value of transaction_analysis.update_operator
     *
     * @mbggenerated
     */
    public String getUpdateOperator() {
        return updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.update_operator
     *
     * @param updateOperator the value for transaction_analysis.update_operator
     *
     * @mbggenerated
     */
    public void setUpdateOperator(String updateOperator) {
        this.updateOperator = updateOperator == null ? null : updateOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_analysis.insert_time
     *
     * @return the value of transaction_analysis.insert_time
     *
     * @mbggenerated
     */
    public String getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_analysis.insert_time
     *
     * @param insertTime the value for transaction_analysis.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime == null ? null : insertTime.trim();
    }
}