package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import java.util.Date;

/**
 * dx
 */
public class WaitSettleRecord extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.shopName
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.order_amount
     *
     * @mbggenerated
     */
    private Long orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.settle_status
     *
     * @mbggenerated
     */
    private Byte settleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.has_settle_amount
     *
     * @mbggenerated
     */
    private Long hasSettleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.no_settle_amount
     *
     * @mbggenerated
     */
    private Long noSettleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.order_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.add_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_settle_record.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.id
     *
     * @return the value of wait_settle_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.id
     *
     * @param id the value for wait_settle_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.order_sn
     *
     * @return the value of wait_settle_record.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.order_sn
     *
     * @param orderSn the value for wait_settle_record.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.order_id
     *
     * @return the value of wait_settle_record.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.order_id
     *
     * @param orderId the value for wait_settle_record.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.order_amount
     *
     * @return the value of wait_settle_record.order_amount
     *
     * @mbggenerated
     */
    public Long getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.order_amount
     *
     * @param orderAmount the value for wait_settle_record.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    public Byte getSettleStatus() {
        return settleStatus;
    }

    public void setSettleStatus(Byte settleStatus) {
        this.settleStatus = settleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.order_time
     *
     * @return the value of wait_settle_record.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.order_time
     *
     * @param orderTime the value for wait_settle_record.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.add_time
     *
     * @return the value of wait_settle_record.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.add_time
     *
     * @param addTime the value for wait_settle_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_settle_record.update_time
     *
     * @return the value of wait_settle_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_settle_record.update_time
     *
     * @param updateTime the value for wait_settle_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    public Long getHasSettleAmount() {
        return hasSettleAmount;
    }

    public void setHasSettleAmount(Long hasSettleAmount) {
        this.hasSettleAmount = hasSettleAmount;
    }

    public Long getNoSettleAmount() {
        return noSettleAmount;
    }

    public void setNoSettleAmount(Long noSettleAmount) {
        this.noSettleAmount = noSettleAmount;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }
}