package com.jusfoun.hookah.core.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jusfoun.hookah.core.generic.GenericModel;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import java.util.Date;

public class WithdrawRecord extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.id
     *
     * @mbggenerated
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.serial_no
     *
     * @mbggenerated
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.money
     *
     * @mbggenerated
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.pay_pwd
     *
     * @mbggenerated
     */
    private String payPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.add_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.check_operator
     *
     * @mbggenerated
     */
    private String checkOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.checck_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date checckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.check_msg
     *
     * @mbggenerated
     */
    private String checkMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.check_status
     *
     * @mbggenerated
     */
    private Byte checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_record.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.id
     *
     * @return the value of withdraw_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.id
     *
     * @param id the value for withdraw_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.user_id
     *
     * @return the value of withdraw_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.user_id
     *
     * @param userId the value for withdraw_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.serial_no
     *
     * @return the value of withdraw_record.serial_no
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.serial_no
     *
     * @param serialNo the value for withdraw_record.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.money
     *
     * @return the value of withdraw_record.money
     *
     * @mbggenerated
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.money
     *
     * @param money the value for withdraw_record.money
     *
     * @mbggenerated
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.pay_pwd
     *
     * @return the value of withdraw_record.pay_pwd
     *
     * @mbggenerated
     */
    public String getPayPwd() {
        return payPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.pay_pwd
     *
     * @param payPwd the value for withdraw_record.pay_pwd
     *
     * @mbggenerated
     */
    public void setPayPwd(String payPwd) {
        this.payPwd = payPwd == null ? null : payPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.add_time
     *
     * @return the value of withdraw_record.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.add_time
     *
     * @param addTime the value for withdraw_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.check_operator
     *
     * @return the value of withdraw_record.check_operator
     *
     * @mbggenerated
     */
    public String getCheckOperator() {
        return checkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.check_operator
     *
     * @param checkOperator the value for withdraw_record.check_operator
     *
     * @mbggenerated
     */
    public void setCheckOperator(String checkOperator) {
        this.checkOperator = checkOperator == null ? null : checkOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.checck_time
     *
     * @return the value of withdraw_record.checck_time
     *
     * @mbggenerated
     */
    public Date getChecckTime() {
        return checckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.checck_time
     *
     * @param checckTime the value for withdraw_record.checck_time
     *
     * @mbggenerated
     */
    public void setChecckTime(Date checckTime) {
        this.checckTime = checckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.check_msg
     *
     * @return the value of withdraw_record.check_msg
     *
     * @mbggenerated
     */
    public String getCheckMsg() {
        return checkMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.check_msg
     *
     * @param checkMsg the value for withdraw_record.check_msg
     *
     * @mbggenerated
     */
    public void setCheckMsg(String checkMsg) {
        this.checkMsg = checkMsg == null ? null : checkMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.check_status
     *
     * @return the value of withdraw_record.check_status
     *
     * @mbggenerated
     */
    public Byte getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.check_status
     *
     * @param checkStatus the value for withdraw_record.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(Byte checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_record.card_no
     *
     * @return the value of withdraw_record.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_record.card_no
     *
     * @param cardNo the value for withdraw_record.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }
}