server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: qddata.com.cn
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false
  host:
    domain: qddata.com.cn
    website: ${server.http.protocal}trade.qddata.com.cn
    static: ${server.http.protocal}static.qddata.com.cn
    auth: ${server.http.protocal}auth.qddata.com.cn
    console: ${server.http.protocal}console.qddata.com.cn
    admin: ${server.http.protocal}admin.qddata.com.cn
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.qddata.com.cn/reg
    loginUrl: http://auth.qddata.com.cn/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.qddata.com.cn/logout?redirect_uri=http://trade.qddata.com.cn/login
    accessTokenUrl: http://auth.qddata.com.cn/oauth/accessToken
    userInfoUrl: http://auth.qddata.com.cn/userInfo
    redirectUrl: http://auth.qddata.com.cn/login
  redis:
    ipPort: 172.16.201.41:7000,172.16.201.41:7001,172.16.201.41:7002
  consul:
    ipPort: 172.16.201.41:8500
debug: true
spring:
  data:
    mongodb:
      uri: mongodb://172.16.201.42:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 172.16.201.41:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /
      listener:
        retry:
          enabled: true
          max-attempts: 2



