server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: cxy.aesdata.cn
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false

  host:
    domain: cxy.aesdata.cn
    website: ${server.http.protocal}trade.cxy.aesdata.cn
    static: ${server.http.protocal}static.cxy.aesdata.cn
    auth: ${server.http.protocal}auth.cxy.aesdata.cn
    console: ${server.http.protocal}console.cxy.aesdata.cn
    admin: ${server.http.protocal}admin.cxy.aesdata.cn
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.cxy.aesdata.cn/reg
    loginUrl: http://auth.cxy.aesdata.cn/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.cxy.aesdata.cn/logout?redirect_uri=http://trade.cxy.aesdata.cn/login
    accessTokenUrl: http://auth.cxy.aesdata.cn/oauth/accessToken
    userInfoUrl: http://auth.cxy.aesdata.cn/userInfo
    redirectUrl: http://auth.cxy.aesdata.cn/login
  redis:
    ipPort: 192.168.16.129:7000,192.168.16.129:7001,192.168.16.129:7002
  consul:
    ipPort: 127.0.0.1:8500
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.16.129:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 192.168.16.129:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /


