server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: xzbdex.com
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false

  host:
    domain: xzbdex.com
    website: ${server.http.protocal}www.xzbdex.com
    static: ${server.http.protocal}static.xzbdex.com
    auth: ${server.http.protocal}auth.xzbdex.com
    console: ${server.http.protocal}console.xzbdex.com
    admin: ${server.http.protocal}admin.xzbdex.com
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.xzbdex.com/reg
    loginUrl: http://auth.xzbdex.com/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.xzbdex.com/logout?redirect_uri=http://www.xzbdex.com/login
    accessTokenUrl: http://auth.xzbdex.com/oauth/accessToken
    userInfoUrl: http://auth.xzbdex.com/userInfo
    redirectUrl: http://auth.xzbdex.com/login
  redis:
    ipPort: 192.168.16.206:7000,192.168.16.206:7001,192.168.16.206:7002
  consul:
    ipPort: 192.168.16.206:8500
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.16.206:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 192.168.16.206:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /
      listener:
        retry:
          enabled: true
          max-attempts: 2
redis:
  ip: 192.168.16.206
  port: 6379
  password: Yqn2ht4DYkMHlDvTY7CV
  pool:
    #最大分配的对象数
    maxTotal: 1024
    #最大能够保持idel状态的对象数
    maxIdle: 200
    #当调用borrow Object方法时，是否进行有效性检查
    testOnBorrow: false


