server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: xzbdex.com
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false
  host:
    domain: xzbdex.com
    website: ${server.http.protocal}trade.xzbdex.com
    static: ${server.http.protocal}static.xzbdex.com
    auth: ${server.http.protocal}auth.xzbdex.com
    console: ${server.http.protocal}console.xzbdex.com
    admin: ${server.http.protocal}admin.xzbdex.com
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.xzbdex.com/reg
    loginUrl: http://auth.xzbdex.com/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.xzbdex.com/logout?redirect_uri=http://trade.xzbdex.com/login
    accessTokenUrl: http://auth.xzbdex.com/oauth/accessToken
    userInfoUrl: http://auth.xzbdex.com/userInfo
    redirectUrl: http://auth.xzbdex.com/login
  redis:
    ipPort: 172.16.201.41:7000,172.16.201.41:7001,172.16.201.41:7002
  consul:
    ipPort: 172.16.201.41:8500
debug: true
spring:
  data:
    mongodb:
      uri: mongodb://172.16.201.42:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 172.16.201.41:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /
      listener:
        retry:
          enabled: true
          max-attempts: 2



