server:
  port: 9000
  http:
    protocal: http://
  session:
    cookie:
      domain: lsdashuju.com
      name: hookah_sid
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix: /
    suffix: .html
    cache: false

  host:
    domain: lsdashuju.com
    website: ${server.http.protocal}trade.lsdashuju.com
    static: ${server.http.protocal}static.lsdashuju.com
    auth: ${server.http.protocal}auth.lsdashuju.com
    console: ${server.http.protocal}console.lsdashuju.com
    admin: ${server.http.protocal}admin.lsdashuju.com
  oauth2:
    clientId: website
    clientSecret: Yqn2ht4DYkMHlDvTY7CV
    regUrl: http://auth.lsdashuju.com/reg
    loginUrl: http://auth.lsdashuju.com/oauth/authorize?client_id=website&response_type=code&redirect_uri=
    logoutUrl: http://auth.lsdashuju.com/logout?redirect_uri=http://trade.lsdashuju.com/login
    accessTokenUrl: http://auth.lsdashuju.com/oauth/accessToken
    userInfoUrl: http://auth.lsdashuju.com/userInfo
    redirectUrl: http://auth.lsdashuju.com/login
  redis:
    ipPort: 192.168.1.201:7000,192.168.1.201:7001,192.168.1.201:7002
  consul:
    ipPort: 127.0.0.1:8500
debug: true
spring:
  data:
    mongodb:
      uri:  mongodb://192.168.1.201:27017/hookah
  mvc:
      static-path-pattern: /static/**
  rabbitmq:
      addresses: 192.168.1.201:5672
      username: root
      password: password
      publisher-confirms: true
      virtual-host: /


