server:
  port: 8000
  http:
    protocal: http://
myconf:
  beetl:
    templatesPath: views/
    contentType: text/html;charset:UTF-8
    prefix:
    suffix: .html
    cache: false

  host:
    server: ${server.http.protocal}localhost:8000
    static: ${server.http.protocal}localhost:8000
    auth: ${server.http.protocal}localhost:8000
    console: ${server.http.protocal}localhost:8000
debug: true
